version: "3.9"
services:
  mongo:
    image: mongo:latest
    container_name: kino-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  flask:
    build: .
    container_name: kino-flask
    depends_on:
      - mongo
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/kino
      - MYSQL_HOST=43.203.218.183
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1234
      - MYSQL_DB=kino
    volumes:
      - .:/app
    command: python app.py

volumes:
  mongo_data: